name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: ./gradlew --no-daemon build

      - name: Upload Skygrid artifact
        uses: actions/upload-artifact@v7.0.1
        if: success()
        with:
          name: skygrid
          path: build/libs/*.jar