name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload Skygrid artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: skygrid
          path: target/skygrid.jar
      - name: Upload Skygrid artifact with dependencies
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: skygrid
          path: target/skygrid-jar-with-dependencies.jar